# Generated by Django 4.2.1 on 2023-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_bloguser_image_remove_bloguser_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
